### ISSUE TITLE
gg l = undefined:5691   "author"

### ISSUE THREAD

**Issue by pierrenel** [qw3rtman/gg#42] opened 2015-04-24 08:15 UTC
$ gg l
undefined:5691
  "author"

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/pierre/.nvm/versions/node/v0.12.0/lib/node_modules/gitgoodies/lib/gg.js:513:22
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

**Comment by gtors** [comment] 2015-04-24 13:12
Duplicate of #38

**Comment by pierrenel** [comment] 2015-04-24 14:29
Whoops!

**Comment by qw3rtman** [comment] 2015-06-24 17:33
Closing this; duplicate of #38.

**Closed as completed by qw3rtman** 2015-06-24 17:33 UTC
Labels: duplicate
